name: Example Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Lint Commit
      env:
        BASE_BRANCH: ${{ github.base_ref }}
      run: git log "origin/$BASE_BRANCH"..HEAD --pretty='format:%s' | npx commitlint

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      name: Cache Node Packages
      id: cache-npm
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install Packages
      run: npm install

    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Run Tests
      run: npm test
