name: Example Workflow

env:
  RELEASE_BRANCH: ${{ github.base_ref }}

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      name: Cache Node Packages
      id: cache-npm
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install Packages
      run: npm install

    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Run Tests
      run: npm test

    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Release
      run: npx semantic-release -d --branches $RELEASE_BRANCH
